export const CITAS_MICROSERVICE = 'CITAS_MICROSERVICE';
export const CLIENTES_MICROSERVICE = 'CLIENTES_MICROSERVICE';
export const EMPLEADOS_MICROSERVICE = 'EMPLEADOS_MICROSERVICE';
export const PAGOS_MICROSERVICE = 'PAGOS_MICROSERVICE';
export const SERVICIOS_MICROSERVICE = 'SERVICIOS_MICROSERVICE';
export const SERVSOLICITADOS_MICROSERVICE = 'SERVSOLICITADOS_MICROSERVICE';